pipeline:
  build:
    image: plugins/docker
    repo: registry.dryusdan.fr/dryusdan/peertube
    registry: registry.dryusdan.fr
    action: build
    tags: 
      - latest

  push:
    image: xataz/docker-drone-plugin
    repo: registry.dryusdan.fr/dryusdan/peertube
    registry: registry.dryusdan.fr
    username: $PRIVATE_LOGIN
    password: $PRIVATE_PASSWORD
    action: push
    when:
      branch: master
      event: [push, tag, deployment]
