pipeline:

  build-debian:
    image: plugins/docker
    registry: registry.dryusdan.fr
    repo: registry.dryusdan.fr/dryusdan/peertube
    dockerfile: Dockerfile.debian
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - debian
      - debian-latest
    
  build-alpine:
    image: plugins/docker
    registry: registry.dryusdan.fr
    repo: registry.dryusdan.fr/dryusdan/peertube
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    tags:
      - alpine-latest
      - alpine

  push:
    image: appleboy/drone-git-push
    branch: master
    remote: git@github.com:Dryusdan/docker-peertube.git
    secrets: [ git_push_ssh_key ]
